### ISSUE TITLE
Tupperbox Commands not Working

### ISSUE THREAD

**Issue by GIitchGlatch** [Runi-c/Tupperbox#122]
Hi I was just wondering how to fix tupper, I tried to type "tuI!heIp" but it dosent work, I have been using tupper for about a year now and dont understand what is happening, Im using MobiIe but idk if its aIso PC, I stiII have to try it out.

**Comment by greysdawn** [comment]
If you're still experiencing this (or experience it in the future), try pinging the bot to make sure it's up and nothing is wrong with it. Either the prefix is different where you're using it, the permissions might've been changed, or the bot was down when you tried to use it

You should also consider joining the [support server](https://discord.com/invite/Z4BHccHhy3) to report any issues there- you'll get a response faster and will get notified of any outages!

**Comment by GIitchGlatch** [comment]
it works now, thanks!

**Comment by greysdawn** [comment]
(very late but) Glad it's working! Gonna go ahead and close this now
