### ISSUE TITLE
Bot down (7/15/2021)

### ISSUE THREAD

**Issue by Nova334** [Runi-c/Tupperbox#125]
The bot is down again, is this maintenance/technical problems or has it been shut down?

**Comment by ariestis** [comment]
Hi, please refer to the support server for comments like these instead of the GitHub! To answer your question, it's maintenance.

**Comment by yourfellowinsomniac** [comment]
Hi, me and my friend were role playing and the bit suddenly stopped working. Is there maintenance being done or something?

**Comment by Runi-c** [comment]
Please join the support server for Tupperbox status updates. https://discord.gg/rHxMbt2
